package lib

import "time"

type Document struct {
	DocumentID     string    `json:"document_id"`
	Filename       string    `json:"filename"`
	Status         string    `json:"status"`
	ModelID        string    `json:"model_id"`
	Source         string    `json:"source"`
	Target         string    `json:"target"`
	WordCount      int       `json:"word_count"`
	CharacterCount int       `json:"character_count"`
	Created        time.Time `json:"created"`
	Completed      time.Time `json:"completed"`
}

type AutoGenerated struct {
	Documents []Document `json:"documents"`
}
